### ISSUE TITLE
change keyboard shortcut

### ISSUE THREAD

**Issue by yurigoytacaz** [StoyanDimitrov/css-reload#2]
Can you provide some settings so we can change the keyboard shortcut?

**Comment by StoyanDimitrov** [comment]
We'll have to wait, I guess: https://bugzil.la/1303384

**Edit** Recently one of the other related bugs got promoted to meta so, probably it is wise to follow https://bugzil.la/1215061 instead.

**Comment by thany** [comment]
Is there a non-UI way to change the hotkey?

**Comment by StoyanDimitrov** [comment]
Well, this bug is only one of plethora of bugs related to browser extension shortcuts customization.
To be frank, I don't want to implement one myself because it won't work reliable. That's why I'm leaning towards browser support.

**Comment by thany** [comment]
Well then maybe change it to F9 to match the old (legacy-)addon CSS Reloader?

**Comment by StoyanDimitrov** [comment]
When the extension was initially implemented it was not possible to use function keys without a modifier. Now it is, but I'm very hesitant to aggravate current users.
It may not sound like but I'm truly concerned about this topic. I'm very well aware that forcing a shortcut without a way to change it is a usability no-on. I'm sure that this alone has turned out not one or two users. Still I prefer that way. Once I have a solid ground (read good browser support for that) I'll implement shortcut customization. This is of utmost importance for the extension and my primary goal.
